#56 : Fixed Tradeskill bar colors.
Kozoaku/XIV_Databar pull request #57
Opened 2023-01-02 17:59 UTC by ZelionGG

Fixed Tradeskill bar colors ([#56](https://github.com/Kozoaku/XIV_Databar/issues/56))

2023-01-24 20:53 UTC, Kozoaku requested changes
The Covenant Hearthstones and Eternal Traveler's Hearthstones are already in the list. Please remove them and I can approve this change.

2023-01-24 23:22 UTC, ZelionGG commented
My bad, duplicates have been removed.

2023-01-25 04:21 UTC, Kozoaku approved these changes

2023-01-25 04:22 UTC, Kozoaku approved these changes

2023-01-25 04:22 UTC, merged